import { webkit, devices } from 'playwright';
const browser = await webkit.launch();
const ctx = await browser.newContext({ ...devices['iPhone 13'] });
const page = await ctx.newPage();
await page.goto('http://localhost:3737/', { waitUntil:'networkidle' });
await page.waitForTimeout(1500);
await page.evaluate(()=>{location.hash='#book/1000005/page/4634';});
await page.waitForTimeout(4500);
const next=page.locator('#editor-card button[aria-label="Nächster Eintrag"],#editor-card button[aria-label="Next entry"]').first();
const prev=page.locator('#editor-card button[aria-label="Vorheriger Eintrag"],#editor-card button[aria-label="Previous entry"]').first();
const title=()=>page.locator('#editor-card .card-title').first().evaluate(e=>e.value??e.textContent).catch(()=>null);
const dim = async (l,n)=>{const b=await l.boundingBox();console.log(n,'box',JSON.stringify(b&&{w:Math.round(b.width),h:Math.round(b.height)}));};
await dim(next,'NEXT'); await dim(prev,'PREV');
console.log('title:', (await title())?.trim());
await next.tap(); await page.waitForTimeout(1000); console.log('after tap next:', (await title())?.trim());
await prev.tap(); await page.waitForTimeout(1000); console.log('after tap prev:', (await title())?.trim());
await page.screenshot({ path:'/tmp/wk-fixed.png' });
await browser.close();
